# Generated by Django 4.2.7 on 2025-05-29 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=50, unique=True)),
                ('title_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('size_hectares', models.DecimalField(decimal_places=4, max_digits=10)),
                ('land_use', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural'), ('industrial', 'Industrial'), ('mixed', 'Mixed Use')], max_length=20)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('pending', 'Pending Registration'), ('disputed', 'Under Dispute'), ('transferred', 'Transfer in Progress')], default='pending', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_parcels', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_parcels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Land Parcel',
                'verbose_name_plural': 'Land Parcels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True)),
                ('transfer_type', models.CharField(choices=[('sale', 'Sale'), ('gift', 'Gift'), ('inheritance', 'Inheritance'), ('exchange', 'Exchange'), ('court_order', 'Court Order'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('transfer_value', models.DecimalField(blank=True, decimal_places=2, help_text='Transfer value in Francs', max_digits=15, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('legal_document_required', models.BooleanField(default=True)),
                ('notary_required', models.BooleanField(default=True)),
                ('court_approval_required', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_as_current_owner', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL)),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_as_new_owner', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_transfers', to='land_management.landparcel')),
            ],
            options={
                'verbose_name': 'Ownership Transfer',
                'verbose_name_plural': 'Ownership Transfers',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
