# Generated by Django 4.2.7 on 2025-06-12 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_parceltitle_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land_management', '0002_remove_landparcel_land_use_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon_geojson', models.TextField(help_text='GeoJSON representation of the polygon boundary')),
                ('center_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('center_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Area in square meters', max_digits=12, null=True)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=4, help_text='Area in hectares', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boundary', to='applications.parcelapplication')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boundaries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_boundaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcel Boundary',
                'verbose_name_plural': 'Parcel Boundaries',
            },
        ),
    ]
