# Generated by Django 4.2.7 on 2025-06-27 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0007_remove_parcelapplication_latitude_and_more'),
        ('land_management', '0003_parcelboundary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownershiptransfer',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='ownershiptransfer',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='ownershiptransfer',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='ownershiptransfer',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='ownershiptransfer',
            name='court_approval_required',
        ),
        migrations.RemoveField(
            model_name='ownershiptransfer',
            name='initiated_by',
        ),
        migrations.RemoveField(
            model_name='ownershiptransfer',
            name='legal_document_required',
        ),
        migrations.RemoveField(
            model_name='ownershiptransfer',
            name='notary_required',
        ),
        migrations.RemoveField(
            model_name='ownershiptransfer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ownershiptransfer',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='ownershiptransfer',
            name='transfer_type',
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='current_owner_id_document',
            field=models.FileField(blank=True, null=True, upload_to='transfers/owner_ids/'),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='new_owner_id_document',
            field=models.FileField(blank=True, null=True, upload_to='transfers/buyer_ids/'),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='other_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='reason',
            field=models.CharField(choices=[('sale', 'Sale'), ('gift', 'Gift'), ('inheritance', 'Inheritance'), ('exchange', 'Exchange'), ('court_order', 'Court Order'), ('other', 'Other')], default='sale', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='receiver_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='receiver_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='receiver_email',
            field=models.EmailField(default='placeholder@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='receiver_first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='receiver_last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='receiver_national_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='receiver_phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='sale_deed',
            field=models.FileField(blank=True, null=True, upload_to='transfers/sale_deeds/'),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='applications.parceltitle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='transfer_certificate',
            field=models.FileField(blank=True, null=True, upload_to='transfers/certificates/'),
        ),
        migrations.AlterField(
            model_name='ownershiptransfer',
            name='current_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_as_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownershiptransfer',
            name='new_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_as_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownershiptransfer',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('awaiting_receiver', 'Awaiting Receiver Confirmation'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='ownershiptransfer',
            name='transfer_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
