# Generated by Django 4.2.7 on 2025-08-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('landowner', 'Landowner'), ('registry_officer', 'Registry Officer'), ('surveyor', 'Surveyor'), ('notary', 'Notary'), ('dispute_officer', 'Dispute Officer'), ('admin', 'Administrator')], default='landowner', max_length=20),
        ),
    ]
