# Generated by Django 4.2.7 on 2025-06-20 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0007_remove_parcelapplication_latitude_and_more'),
        ('signatures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land_management', '0003_parcelboundary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('certificate_type', models.CharField(choices=[('property_contract', 'Property Contract'), ('parcel_certificate', 'Parcel Certificate')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificates/qr_codes/')),
                ('document_hash', models.CharField(blank=True, help_text='SHA-256 hash of the PDF', max_length=256)),
                ('blockchain_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='applications.parcelapplication')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='land_management.landparcel')),
                ('signatures', models.ManyToManyField(blank=True, related_name='certificates', to='signatures.digitalsignature')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('certificate_type', models.CharField(choices=[('property_contract', 'Property Contract'), ('parcel_certificate', 'Parcel Certificate')], max_length=30, unique=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='certificates/templates/logos/')),
                ('watermark_image', models.ImageField(blank=True, null=True, upload_to='certificates/templates/watermarks/')),
                ('border_image', models.ImageField(blank=True, null=True, upload_to='certificates/templates/borders/')),
                ('primary_color', models.CharField(default='#000080', max_length=7)),
                ('secondary_color', models.CharField(default='#FFD700', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('header_font', models.CharField(default='Helvetica-Bold', max_length=50)),
                ('body_font', models.CharField(default='Helvetica', max_length=50)),
                ('layout_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Templates',
            },
        ),
        migrations.CreateModel(
            name='CertificateAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('issued', 'Issued'), ('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('verified', 'Verified'), ('revoked', 'Revoked'), ('expired', 'Expired')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='certificates.certificate')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate Audit Log',
                'verbose_name_plural': 'Certificate Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
