# Generated by Django 4.2.7 on 2025-06-02 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land_management', '0002_remove_landparcel_land_use_and_more'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('owner_first_name', models.CharField(max_length=100)),
                ('owner_last_name', models.CharField(max_length=100)),
                ('property_address', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=100)),
                ('application_type', models.CharField(choices=[('property_contract', 'Property Contract'), ('parcel_certificate', 'Parcel Certificate')], max_length=30)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('field_inspection', 'Field Inspection'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_applications', to=settings.AUTH_USER_MODEL)),
                ('field_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_parcel_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcel Application',
                'verbose_name_plural': 'Parcel Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ParcelTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_number', models.CharField(max_length=50, unique=True)),
                ('title_type', models.CharField(choices=[('property_contract', 'Property Contract'), ('parcel_certificate', 'Parcel Certificate')], max_length=30)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_titles', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='land_management.landparcel')),
            ],
            options={
                'verbose_name': 'Parcel Title',
                'verbose_name_plural': 'Parcel Titles',
            },
        ),
        migrations.CreateModel(
            name='ParcelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('owner_id', 'Owner ID'), ('sale_deed', 'Sale Deed'), ('previous_contract', 'Previous Property Contract')], max_length=30)),
                ('file', models.FileField(upload_to='parcel_applications/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.parcelapplication')),
            ],
            options={
                'verbose_name': 'Parcel Document',
                'verbose_name_plural': 'Parcel Documents',
            },
        ),
    ]
