# Generated by Django 4.2.7 on 2025-06-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_parcelapplication_parceltitle_parceldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelapplication',
            name='application_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parceltitle',
            name='title_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
