# Generated by Django 4.2.7 on 2025-06-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_parcelapplication_application_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('field_inspection', 'Field Inspection'), ('inspection_completed', 'Inspection Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
