# Generated by Django 4.2.7 on 2025-06-11 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_add_inspection_completed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceltitle',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='applications.parcelapplication'),
        ),
    ]
