# Generated by Django 4.2.7 on 2025-06-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_parceltitle_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelapplication',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parcelapplication',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parcelapplication',
            name='size_hectares',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parcelapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('field_inspection', 'Field Inspection'), ('inspection_completed', 'Inspection Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=25),
        ),
    ]
