# Generated by Django 4.2.7 on 2025-06-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_parcelapplication_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelapplication',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='parcelapplication',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='parcelapplication',
            name='size_hectares',
        ),
        migrations.AlterField(
            model_name='parcelapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('field_inspection', 'Field Inspection'), ('inspection_completed', 'Inspection Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
