# Generated by Django 4.2.7 on 2025-07-08 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0004_remove_ownershiptransfer_approval_date_and_more'),
        ('applications', '0007_remove_parcelapplication_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelapplication',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parcelapplication',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parcelapplication',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_applications', to='land_management.landparcel'),
        ),
        migrations.AddField(
            model_name='parcelapplication',
            name='size_hectares',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
