# Generated by Django 4.2.7 on 2025-05-29 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
        ('applications', '0001_initial'),
        ('land_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_hash', models.CharField(help_text='SHA-256 hash of the document', max_length=256)),
                ('signature_hash', models.CharField(help_text='Digital signature hash', max_length=512)),
                ('document_type', models.CharField(choices=[('title_deed', 'Title Deed'), ('transfer_agreement', 'Transfer Agreement'), ('application_approval', 'Application Approval'), ('dispute_resolution', 'Dispute Resolution'), ('legal_document', 'Legal Document'), ('other', 'Other')], max_length=30)),
                ('document_title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('invalid', 'Invalid'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('certificate_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_issuer', models.CharField(blank=True, max_length=200, null=True)),
                ('certificate_valid_from', models.DateTimeField(blank=True, null=True)),
                ('certificate_valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_timestamp', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='applications.titleapplication')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='documents.document')),
                ('related_parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='land_management.landparcel')),
                ('related_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='land_management.ownershiptransfer')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Digital Signature',
                'verbose_name_plural': 'Digital Signatures',
                'ordering': ['-signed_at'],
            },
        ),
    ]
