# Generated by Django 4.2.7 on 2025-06-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalsignature',
            name='signature_image',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image', null=True),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='signature_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional signature metadata'),
        ),
        migrations.AlterField(
            model_name='digitalsignature',
            name='signature_hash',
            field=models.TextField(help_text='Digital signature data'),
        ),
    ]
