# Generated by Django 4.2.7 on 2025-06-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_alter_dispute_dispute_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='respondent_name',
            field=models.CharField(blank=True, help_text='Name of the respondent (person against whom the dispute is filed)', max_length=200, null=True),
        ),
    ]
