# Generated by Django 4.2.7 on 2025-08-10 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land_management', '0004_remove_ownershiptransfer_approval_date_and_more'),
        ('applications', '0008_parcelapplication_latitude_and_more'),
        ('disputes', '0003_dispute_respondent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='approach_notes',
            field=models.TextField(blank=True, help_text='Additional guidance for the assigned officer', null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='approach_suggested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='approach_suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_approaches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='suggested_approach',
            field=models.CharField(blank=True, choices=[('direct_mediation', 'Direct Mediation - Face-to-face discussion'), ('shuttle_mediation', 'Shuttle Mediation - Separate meetings'), ('technical_investigation', 'Technical Investigation - Survey/documentation'), ('documentary_review', 'Documentary Review - Legal documents focus'), ('site_inspection', 'Site Inspection - Physical verification'), ('multi_party_conference', 'Multi-Party Conference - Multiple stakeholders'), ('traditional_resolution', 'Traditional Resolution - Local leaders involvement'), ('fast_track', 'Fast Track - Quick resolution for simple cases'), ('complex_investigation', 'Complex Investigation - Extensive research required')], help_text='Recommended approach for resolving this dispute', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='land_management.landparcel'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='related_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.parcelapplication'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_against', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ApproachEffectiveness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_type', models.CharField(choices=[('boundary', 'Boundary Dispute'), ('ownership', 'Ownership Dispute'), ('encroachment', 'Encroachment'), ('inheritance', 'Inheritance Dispute'), ('fraud', 'Fraudulent Transaction'), ('other', 'Other')], max_length=20)),
                ('approach', models.CharField(choices=[('direct_mediation', 'Direct Mediation - Face-to-face discussion'), ('shuttle_mediation', 'Shuttle Mediation - Separate meetings'), ('technical_investigation', 'Technical Investigation - Survey/documentation'), ('documentary_review', 'Documentary Review - Legal documents focus'), ('site_inspection', 'Site Inspection - Physical verification'), ('multi_party_conference', 'Multi-Party Conference - Multiple stakeholders'), ('traditional_resolution', 'Traditional Resolution - Local leaders involvement'), ('fast_track', 'Fast Track - Quick resolution for simple cases'), ('complex_investigation', 'Complex Investigation - Extensive research required')], max_length=30)),
                ('success_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('average_resolution_days', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Approach Effectiveness',
                'verbose_name_plural': 'Approach Effectiveness Records',
                'unique_together': {('dispute_type', 'approach')},
            },
        ),
    ]
